theme: minima
markdown: kramdown

title: Learning Purely Tactile In-Hand Manipulation
author: "{leon.sievers,johannes.pitz,lennart.roestel,berthold.baeuml}@dlr.de"

header_pages:
  - index.md
  - _pages/lab.md
  - _pages/icra22.md
  - _pages/icra23.md
  - _pages/humanoids23.md
  # - _pages/iros24.md

include:
    - _pages
    
plugins:
  - jekyll-redirect-from

exclude:
    - .gitignore
    - Gemfile
    - README.md
